import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";

export default function Home() {
  const [message, setMessage] = useState('start')

  useEffect(() => {
    (async() => {
      fetch('/api/hello', {method: 'POST', body: JSON.stringify({name: 'VASYA'})})
    })()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {message}
      </div>
    </>
  );
}
